#!/bin/sh

set -e

if ! test -e corrode/corrode.cabal; then
	git submodule update --init
fi

cabal sandbox init
cabal sandbox add-source corrode
cabal --require-sandbox install corrode

if ! test -e config.status; then
	autoreconf -if
	./configure --with-external-zlib
fi

PATH=".cabal-sandbox/bin:$PATH" make CC="`pwd`/corrode/scripts/corrode-cc"
