#!/bin/sh

set -e

if ! test -e corrode/corrode.cabal; then
	git submodule update --init
fi

quilt push build.patch

cabal sandbox init
cabal sandbox add-source corrode
cabal --require-sandbox install corrode

if ! test -x config.status; then
	autoreconf -if
	./configure --with-external-zlib
else
	automake
	./config.status
fi

PATH="`pwd`/.cabal-sandbox/bin:$PATH" make
